3.6: update gamescope
Update Changes (29.60 MiB):
- gamescope-3.14.26-2.src.tar.gz (29.60 MiB)

diff --git a/gamescope/gamescope-session b/gamescope/gamescope-session
--- a/gamescope/gamescope-session
+++ b/gamescope/gamescope-session
@@ -308,15 +308,20 @@ SECONDS=0
 short_session_count=$(< "$short_session_tracker_file" wc -l)
 
 if [[ "$short_session_count" -ge "$short_session_count_before_reset" ]]; then
-	# TODO could detect if we're in the devkit case below and undo that instead
-	# instead of resetting the wrong thing
-	# also could print full list of files and sizes in the Steam dir and save as a diagnostic report
 	echo >&2 "gamescope-session: detected broken Steam, bootstrapping from OS copy..."
 	# at this point, might as well make sure we won't relaunch on a sideloaded build
 	rm -f -- "$HOME/devkit-game/devkit-steam"
 	mkdir -p ~/.local/share/Steam
 	# remove some caches and stateful things known to cause Steam to fail to start if corrupt
 	rm -rf --one-file-system ~/.local/share/Steam/config/widevine
+	# cleanup the steam config dir, i.e. ~/.steam. We should try to preserve registry.vdf if possible
+	steam_config_dir="$HOME/.steam"
+	steam_config_backup_dir="$HOME/dot-steam.bak.$(date +%s)"
+	registry_vdf="$steam_config_dir/registry.vdf"
+	registry_backup_vdf="$steam_config_backup_dir/.steam/registry.vdf"
+	mv "$steam_config_dir" "$steam_config_backup_dir"
+	mkdir -p "$steam_config_dir"
+	cp -f "$registry_backup_vdf" "$registry_vdf" || true
 	# restore clean copy of binaries from RO partition
 	tar xf /usr/lib/steam/bootstraplinux_ubuntu12_32.tar.xz -C ~/.local/share/Steam
 	# rearm
