3.8: update jupiter-legacy-support
Update Changes (0.01 MiB):
- jupiter-legacy-support-1.156.2-1.src.tar.gz (0.01 MiB)

diff --git a/jupiter-legacy-support/steamos-prepare-oobe-test b/jupiter-legacy-support/steamos-prepare-oobe-test
--- a/jupiter-legacy-support/steamos-prepare-oobe-test
+++ b/jupiter-legacy-support/steamos-prepare-oobe-test
@@ -44,7 +44,7 @@ log "Target OOBE image: $url"
 ## Do the install
 log "Installing '$url' to other slot"
 
-cmd steamos-atomupd-client -d --update-from-url="$url" || die "Install failed, see above."
+cmd atomupd-manager custom-update "$url" --verbose || die "Install failed, see above."
 
 if [[ -n $arg_clean ]]; then
   log "--clean specified, removing network configurations from remote side"
